<a href="https://colab.research.google.com/github/wlgns222/ROKA/blob/main/ai-study/deep-learning-from-scratch-vol2/Ch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ch1. 신경망 복습**

밑바닥부터 시작하는 딥러닝1에 대한 복습

## 1.1 파이썬과 수학 복습

### 1.1.1 벡터와 행렬

**벡터** : 크기와 방향을 가진 양. 숫자가 일렬로 늘어선 형태로 표현가능하며, 파이썬에서는 1차원 배열로 취급할 수 있습니다.

**행렬** : 숫자가 2차원 형태로 늘어선 것이다. 파이썬에서는 2차원 배열로 표현할 수 있다. 가로줄을 행, 세로줄을 열이라고 한다.

파이썬에서 벡터와 행렬은 np.array 에서 생성할 수 있다.

In [1]:
import numpy as np

x = np.array([1, 2, 3])
print(x.shape) # 배열의 형상
print(x.ndim) # 차원 수

W = np.array ([[1,2,3], [4,5,6]])
print(W.shape) # 배열의 형상
print(W.ndim) # 차원 수

(3,)
1
(2, 3)
2


### 1.1.2 행렬의 원소별 계산

In [5]:
X = np.array ([[0,1,2], [3,4,5]])

print("원소별 합 \n", W + X)
print("원소별 곱 \n", W * X)

원소별 합 
 [[ 1  3  5]
 [ 7  9 11]]
원소별 곱 
 [[ 0  2  6]
 [12 20 30]]


### 1.1.3 브로드캐스트

In [9]:
A = np.array([[1,2], [3,4]])
print(A*10)

[[10 20]
 [30 40]]


위 예시에서 스칼라 값 10 은 2x2 행렬로 확장된 후 원소별 연산을 수행한다.

이 영리한 기능을 **브로드캐스트** 라고 한다.

### 1.1.4 벡터의 내적과 행렬의 곱

## 1.2 신경망의 추론

## 1.3 신경망의 학습

## 1.4 신경망으로 문제를 풀다

## 1.5 계산 고속화

## 1.6 정리